"""empty message

Revision ID: a793c3419f65
Revises: 
Create Date: 2025-05-21 15:41:06.755883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a793c3419f65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=80), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('ayarlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayar_adi', sa.String(length=100), nullable=False),
    sa.Column('ayar_degeri', sa.String(length=255), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ayar_adi')
    )
    op.create_table('isletmeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isletme_adi', sa.String(length=200), nullable=False),
    sa.Column('yetkili_kisi', sa.String(length=150), nullable=True),
    sa.Column('isletme_telefon', sa.String(length=20), nullable=False),
    sa.Column('isletme_email', sa.String(length=120), nullable=False),
    sa.Column('isletme_adres', sa.Text(), nullable=True),
    sa.Column('kullanici_adi', sa.String(length=80), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('isletme_kodu', sa.String(length=10), nullable=False),
    sa.Column('son_kargo_no', sa.Integer(), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isletme_email'),
    sa.UniqueConstraint('isletme_kodu'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('kuryeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=150), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=80), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kullanici_adi'),
    sa.UniqueConstraint('telefon')
    )
    op.create_table('bildirimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('isletme_id', sa.Integer(), nullable=True),
    sa.Column('kurye_id', sa.Integer(), nullable=True),
    sa.Column('mesaj', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('okundu_mu', sa.Boolean(), nullable=False),
    sa.Column('bildirim_tipi', sa.String(length=50), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['isletme_id'], ['isletmeler.id'], ),
    sa.ForeignKeyConstraint(['kurye_id'], ['kuryeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isletme_odemeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isletme_id', sa.Integer(), nullable=False),
    sa.Column('odeme_tarihi', sa.Date(), nullable=False),
    sa.Column('odenen_tutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('islem_referansi', sa.String(length=100), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['isletme_id'], ['isletmeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kargolar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isletme_id', sa.Integer(), nullable=False),
    sa.Column('takip_numarasi', sa.String(length=50), nullable=False),
    sa.Column('alici_adi_soyadi', sa.String(length=150), nullable=False),
    sa.Column('alici_telefon', sa.String(length=20), nullable=False),
    sa.Column('alici_email', sa.String(length=120), nullable=True),
    sa.Column('alici_adres', sa.Text(), nullable=False),
    sa.Column('alici_sehir', sa.String(length=100), nullable=False),
    sa.Column('alici_ilce', sa.String(length=100), nullable=True),
    sa.Column('urun_bedeli_alici_tahsil', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kargo_ucreti_isletme_borcu', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kargo_ucreti_alici_tahsil', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('toplam_tahsil_edilecek_alici', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('isletmeye_aktarilacak_tutar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('odeme_yontemi_teslimde', sa.String(length=50), nullable=True),
    sa.Column('odeme_durumu_alici', sa.String(length=50), nullable=False),
    sa.Column('kargo_durumu', sa.Enum('HAZIRLANIYOR', 'PAKETLENDI', 'KURYE_TESLIM_HAZIR', 'MUSTERIDEN_ALINMAYI_BEKLIYOR', 'KARGO_ALINDI_MERKEZDE', 'DAGITIMDA', 'TESLIM_EDILDI', 'TESLIM_EDILEMEDI_ALICI_ULASILAMADI', 'TESLIM_EDILEMEDI_ADRES_HATALI', 'IADE_SURECINDE', 'IADE_EDILDI_ISLETMEYE', 'IPTAL_EDILDI_ISLETME', 'IPTAL_EDILDI_ADMIN', name='kargodurumenum'), nullable=False),
    sa.Column('ozel_not', sa.Text(), nullable=True),
    sa.Column('planlanan_teslim_tarihi', sa.Date(), nullable=True),
    sa.Column('teslim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('pdf_yolu', sa.String(length=255), nullable=True),
    sa.Column('isletmeye_aktarildi_mi', sa.Boolean(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kurye_id', sa.Integer(), nullable=True),
    sa.Column('alici_gecici_enlem', sa.Float(), nullable=True),
    sa.Column('alici_gecici_boylam', sa.Float(), nullable=True),
    sa.Column('alici_gecici_konum_zamani', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['isletme_id'], ['isletmeler.id'], ),
    sa.ForeignKeyConstraint(['kurye_id'], ['kuryeler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('takip_numarasi')
    )
    op.create_table('odeme_kargo_iliskileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odeme_id', sa.Integer(), nullable=False),
    sa.Column('kargo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kargo_id'], ['kargolar.id'], ),
    sa.ForeignKeyConstraint(['odeme_id'], ['isletme_odemeleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odeme_kargo_iliskileri')
    op.drop_table('kargolar')
    op.drop_table('isletme_odemeleri')
    op.drop_table('bildirimler')
    op.drop_table('kuryeler')
    op.drop_table('isletmeler')
    op.drop_table('ayarlar')
    op.drop_table('admin_kullanicilar')
    # ### end Alembic commands ###
